---

- name: Check geth binary
  ansible.builtin.stat:
    path: /usr/bin/geth
  register: geth_binary_file

- name: Stop geth service
  ansible.builtin.systemd:
    state: stopped
    name: geth.service
  when: geth_binary_file.stat.exists

- name: Cleanup systemd config file
  ansible.builtin.file:
    path: /etc/systemd/system/geth.service
    state: absent

- name: Configure systemd
  ansible.builtin.template:
    src: systemd-config.j2
    dest: /etc/systemd/system/geth.service
    owner: root
    group: root
    remote_src: no

- name: Configure systemd (symlink)
  ansible.builtin.file:
    src: /etc/systemd/system/geth.service
    dest: /etc/systemd/system/multi-user.target.wants/geth.service
    owner: root
    group: root
    state: link

- name: Run geth service
  ansible.builtin.systemd:
    state: restarted
    daemon_reload: yes
    name: geth.service
