---
- name: Install Prometheus
  include_tasks:
    file: prometheus.yml
    apply:
      tags:
        - never
        - install-prometheus
  tags:
    - never
    - install-prometheus

- name: Install AlertManager
  include_tasks:
    file: alertmanager.yml
    apply:
      tags:
        - never
        - install-alertmanager
  tags:
    - never
    - install-alertmanager

- name: Install BlackBox
  include_tasks:
    file: blackbox-exporter.yml
    apply:
      tags:
        - never
        - install-blackbox-exporter
  tags:
    - never
    - install-blackbox-exporter

- name: Install NodeExporter
  include_tasks:
    file: node-exporter.yml
    apply:
      tags:
        - never
        - install-node-exporter
  tags:
    - never
    - install-node-exporter

- name: Install Grafana
  include_tasks:
    file: grafana.yml
    apply:
      tags:
        - never
        - install-grafana
  tags:
    - never
    - install-grafana

- name: Install Nginx Proxy
  include_tasks:
    file: nginx-proxy.yml
    apply:
      tags:
        - never
        - install-nginx-proxy
  tags:
    - never
    - install-nginx-proxy