---
- name: Creating prometheus user group
  group: name="{{ prometheus_groupId }}"
  become: true

- name: Creating prometheus user
  user:
    name: "{{ prometheus_userId }}"
    group: "{{ prometheus_groupId }}"
    system: yes
    shell: "/sbin/nologin"
    comment: "{{ prometheus_userId }} nologin User"
    createhome: "no"
    state: present

- name: Install prometheus
  unarchive:
    src: "https://github.com/prometheus/prometheus/releases/download/v{{ prometheus_version }}/prometheus-{{ prometheus_version }}.linux-amd64.tar.gz"
    dest: /tmp/
    remote_src: yes

- name: Copy prometheus file to bin
  copy:
    src: "/tmp/prometheus-{{ prometheus_version }}.linux-amd64/prometheus"
    dest: "/usr/local/bin/prometheus"
    owner: "{{ prometheus_userId }}"
    group: "{{ prometheus_groupId }}"
    remote_src: yes
    mode: 0755

- name: Delete prometheus tmp folder
  file:
    path: '/tmp/prometheus-{{ prometheus_version }}.linux-amd64'
    state: absent

- name: Creates directory
  file: 
    path: "/data/prometheus/"
    state: directory
    owner: "{{ prometheus_userId }}"
    group: "{{ prometheus_groupId }}"
    mode: 0755

- name: Creates directory
  file: 
    path: "/etc/prometheus/"
    state: directory
    owner: "{{ prometheus_userId }}"
    group: "{{ prometheus_groupId }}"
    mode: 0755

- name: config file
  template:
    src: prometheus-default-config.j2
    dest: /etc/prometheus/prometheus.conf

##### Enable when rules are defined
# - name: alert config file
#   template:
#     src: alertmanager-default-config.j2
#     dest: /etc/prometheus/alert.rules.yml

- name: Copy systemd init file
  template:
    src: prometheus-systemd-config.j2
    dest: /etc/systemd/system/prometheus.service

- name: Start prometheus service
  service:
    name: prometheus
    state: restarted
    enabled: yes

- name: Check if prometheus is accessible
  uri:
    url: http://localhost:9090
    method: GET
    status_code: 200