---

- name: Copy script to the target host
  ansible.builtin.template:
    scr: snapshot-installer.j2
    dest: snapshot-installer.sh
    mode: '0777'

- name: Execute script
  command: bash snapshot-installer.sh
  become: yes

- name: Debug Message
  ansible.builtin.debug:
    msg: "Installing Heimdall and Bor snapshot can take at least 4-5 hours..."
