---

- name: Copy script to the target host
  ansible.builtin.template:
    src: snapshot-installer.j2
    dest: snapshot-installer.sh
    remote_src: no
    mode: '0777'

- name: Execute script
  shell: "nohup bash {{ root_dir }}/snapshot-installer.sh > nohup.out 2>&1 &"
  become: yes
  async: 60
  poll: 0

- name: Debug Message
  ansible.builtin.debug:
    msg: "Installing Heimdall and Bor snapshot can take at least 4-5 hours..."
