---

- name: Install update
  apt:
    update_cache: yes

- name: Install Wget
  apt: 
    name: wget
    state: present

- name: Install build-essential
  apt:
    name: build-essential
    state: present

- name: Install make
  apt:
    name: make
    state: present

- name: Install gcc
  apt:
    name: gcc
    state: present

- name: Install git
  apt:
    name: git
    state: present

- name: Check golang binary
  ansible.builtin.stat:
    path: /usr/local/go
  register: golang_binary_file

- name: Install golang
  ansible.builtin.template:
    src: go-installer.j2
    dest: /tmp/go-installer.sh
    owner: root
    group: root
    remote_src: no
  when: not golang_binary_file.stat.exists

- name: Make script executable
  ansible.builtin.file:
    path: /tmp/go-install.sh
    mode: 0777
  when: not golang_binary_file.stat.exists

- name: Run command
  ansible.builtin.command: /tmp/go-install.sh
  become: true
  when: not golang_binary_file.stat.exists

- name: Create symlink
  ansible.builtin.command: ln -nfs ~/.go/bin/go /usr/bin/go
  become: true
  when: not golang_binary_file.stat.exists
