---

- name: Copy script to the target host
  ansible.builtin.template:
    src: snapshot-installer.j2
    dest: snapshot-installer.sh
    remote_src: no
    mode: '0777'

- name: Execute script
  shell: bash snapshot-installer.sh
  become: yes
  async: 30
  poll: 0

- name: Debug Message
  ansible.builtin.debug:
    msg: "Installing Heimdall and Bor snapshot can take at least 4-5 hours..."
