---

# tasks file for heimdall
- name: Clone the Heimdall
  git:
    repo: "https://github.com/maticnetwork/heimdall.git"
    dest: "{{ root_dir }}/heimdall"
    force: yes
    version: "{{ heimdall_branch }}"

- name: Build heimdall
  command: chdir={{ root_dir }}/heimdall make install network={{ heimdall_network }}

- name: Creating symlink for heimdalld
  file:
    src: "{{ root_dir }}/go/bin/heimdalld"
    dest: "/usr/bin/heimdalld"
    state: link
  become: true

- name: Creating symlink for heimdallcli
  file:
    src: "{{ root_dir }}/go/bin/heimdallcli"
    dest: "/usr/bin/heimdallcli"
    state: link
  become: true

- name: Creating symlink for bridge
  file:
    src: "{{ root_dir }}/go/bin/bridge"
    dest: "/usr/bin/bridge"
    state: link
  become: true

# tasks file for bor
- name: Cloning the Bor
  git:
    repo: "https://github.com/maticnetwork/bor.git"
    dest: "{{ root_dir }}/bor"
    force: yes
    version: "{{ bor_branch }}"

- name: Build Bor
  command: chdir={{ root_dir }}/bor make bor-all

- name: Creating symlink for bor
  file:
    src: "{{ root_dir }}/bor/build/bin/bor"
    dest: "/usr/bin/bor"
    state: link
  become: true

- name: Creating symlink for bootnode
  file:
    src: "{{ root_dir }}/bor/build/bin/bootnode"
    dest: "/usr/bin/bootnode"
    state: link
  become: true

# Restart Services
- name: Reload heimdalld
  notify: reload heimdalld

- name: Reload heimdalld-rest-server
  notify: reload heimdalld-rest-server

- name: Reload heimdalld-bridge
  notify: reload heimdalld-bridge

- name: Reload bor
  notify: reload bor
