---

- name: Log bash configuration
  debug: 
    msg: About to begin bash configuration

- name: Update apt cache
  become: true
  apt: 
    update_cache: yes

- name: Curl Route Installation
  command: curl https://deb.releases.teleport.dev/teleport-pubkey.asc -o {{ archive_keyring }}

- name: Creation of teleport.list
  become: true
  tags: addfile
  file:
    path: '{{ teleportlist_route }}'
    state: touch

- name: Insert route on teleport.list
  become: true
  tags: adddata
  lineinfile:
    path: '{{ teleportlist_route }}'
    line: "deb [signed-by={{ archive_keyring }}] https://deb.releases.teleport.dev/ stable main"
    state: present
    backup: yes
  register: addTeleport

- name: Update APT package
  apt: 
    update_cache: yes

- name: Install python3-dnf
  apt:
    name: python3-dnf
    state: present

- name: Install Teleport
  apt:
    name: teleport
    state: present

   
