---

- name: Install Teleport dependencies
  include_tasks:
    file: install-teleport-dep.yml
    apply:
      tags:
        - never
        - install-teleport-dep
  tags:
    - never
    - install-teleport-dep

- name: Install Teleport
  include_tasks: 
    file: install-teleport.yml
    apply:
      tags:
        - never
        - install-teleport
  tags:
    - never
    - install-teleport

- name: Configure Teleport
  include_tasks: 
    file: config-teleport.yml
    apply:
      tags:
        - never
        - config-teleport
  tags:
    - never
    - config-teleport
