---

- name: Install prerequisites
  include_task: install-dependency-teleport.yml

- name: Install teleport-config
  include_task: config-teleport.yml

- name: Install teleport-installation
  include_task: install-teleport.yml
