---

- name: Check matic snapshot
  include_tasks: 
    file: matic-snapshot-checker.yml
    apply:
      tags: 
        - never
        - matic-snapshot-checker
  tags:
    - never 
    - matic-snapshot-checker

- name: Check btc block
  include_tasks: 
    file: btc-block-checker.yml
    apply:
      tags: 
        - never
        - btc-block-checker
  tags:
    - never 
    - btc-block-checker
