---

- name: Check storage space
  shell: df -h

- name: Check data_dir size (Heimdall)
  shell: du -sch {{ root_dir }}/.heimdalld/data/

- name: Check data_dir size (Bor)
  shell: du -sch {{ root_dir }}/.bor/data/bor/chaindata/
