---

- name: Install update
  apt:
    update_cache: yes

- name: Install Git
  apt: 
    name: git
    state: present

- name: Install Setup-tools
  apt:
    name: python3-setuptools
    state: present

- name: Install Python-pip
  apt:
    name: python3-pip
    state: present
