---

- name: Install update
  apt:
    update_cache: yes

- name: Install Git
  apt: 
    name: git
    state: present

- name: Install curl
  apt:
    name: curl
    state: present

- name: Install clang
  apt:
    name: clang
    state: present

- name: Install cmake
  apt:
    name: cmake
    state: present

- name: Install build-essential
  apt:
    name: build-essential
    state: present

- name: Install python3-pip
  apt:
    name: python3-pip
    state: present

- name: Install nginx
  apt:
    name: nginx
    state: present

- name: Install tor
  apt:
    name: tor
    state: present
