---

- name: Cleanup existing files/folders
  ansible.builtin.file:
    path: "{{ root_dir }}/electrumx"

- name: Clone electrumx repo
  ansible.builtin.git:
    repo: "https://github.com/kyuupichan/electrumx.git"
    dest: "{{ root_dir }}"
    clone: yes
    update: yes
    force: yes

- name: Install electrumx
  shell: cd electrumx; pip3 install --user -r requirements.txt

- name: Copy electrumx binary
  shell: cd electrumx; cp electrumx_server /usr/local/bin/
  become: yes

- name: Change file ownership
  shell: chown root:root /usr/local/bin/electrumx_server
  become: yes

- name: Make sure data_dir exist
  ansible.builtin.file:
    path: "{{ electrumx_data_path }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0775"

- name: Configure systemd
  ansible.builtin.template:
    src: electrumx-systemd-config.j2
    dest: /etc/systemd/system/electrumx.service
    owner: root
    group: root
    remote_src: no

- name: Configure electrumx-config
  ansible.builtin.template:
    src: electrumx-config.j2
    dest: "{{ electrumx_data_path }}/electrumx.conf"
    owner: root
    group: root
    remote_src: no

- name: Configure systemd (symlink)
  ansible.builtin.file:
    src: /etc/systemd/system/electrumx.service
    dest: /etc/systemd/system/multi-user.target.wants/electrumx.service
    owner: root
    group: root
    state: link

- name: Run electrumx service
  ansible.builtin.systemd:
    state: restarted
    daemon_reload: yes
    name: electrumx.service
  async: 60
  poll: 0