---

- name: Make sure electrum root_dir exist
  ansible.builtin.file:
    path: "{{ root_dir }}/.electrs"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0775"

- name: Make sure data_dir exist
  ansible.builtin.file:
    path: "{{ electrum_data_path }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0775"

- name: Make sure conf_dir exist
  ansible.builtin.file:
    path: "{{ electrum_conf_path }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0775"

- name: Make sure certs_dir exist
  ansible.builtin.file:
    path: "{{ electrum_cert_path }}"
    state: directory
    owner: root
    group: root
    mode: "0775"

- name: Check if .cargo exist
  stat:
    path: "{{ root_dir }}/.cargo"
  register: cargo_dir

- name: Install Rust
  shell: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
  become: no
  when: cargo_dir.stat.isdir is not defined

- name: Check if ssl cert/key exist
  stat:
    path: "{{ electrum_cert_path }}/cert.pem"
  register: ssl_cert
  
- name: Create ssl cert/key
  shell: |
    cd {{ electrum_cert_path }}
    openssl req -x509 -newkey rsa:4096 -keyout key.pem -out cert.pem -sha256 \
      -days 999 -nodes -subj "/C=US/ST=Florida/L=Stockholm/O=.../OU=.../CN=.../emailAddress=..."
  become: yes
  when: not ssl_cert

- name: Remove default nginx.conf
  ansible.builtin.file:
    path: /etc/nginx/nginx.conf
    state: absent
  become: yes

- name: Configure nginx.conf
  ansible.builtin.template:
    src: nginx-config.j2
    dest: "/etc/nginx/nginx.conf"
    owner: root
    group: root
    remote_src: no
  become: yes

- name: Cleanup existing files/folders
  ansible.builtin.file:
    path: "{{ root_dir }}/electrs"
    state: absent

- name: Clone electrs repo
  ansible.builtin.git:
    repo: "https://github.com/romanz/electrs.git"
    dest: "{{ root_dir }}/electrs"
    clone: yes
    update: yes
    force: yes
  become: no

- name: Install electrs
  shell: cd electrs; ROCKSDB_INCLUDE_DIR=/usr/include ROCKSDB_LIB_DIR=/usr/lib {{ root_dir }}/.cargo/bin/cargo build --locked --release
  become: no

- name: Configure systemd
  ansible.builtin.template:
    src: electrs-systemd-config.j2
    dest: /etc/systemd/system/electrs.service
    owner: root
    group: root
    remote_src: no

- name: Configure electrs-config
  ansible.builtin.template:
    src: electrs-config.j2
    dest: "{{ electrum_conf_path }}/electrs.conf"
    owner: root
    group: root
    remote_src: no

- name: Configure systemd (symlink)
  ansible.builtin.file:
    src: /etc/systemd/system/electrs.service
    dest: /etc/systemd/system/multi-user.target.wants/electrs.service
    owner: root
    group: root
    state: link

- name: Run electrs service
  ansible.builtin.systemd:
    state: restarted
    daemon_reload: yes
    name: electrs.service

- name: Remove default nginx.conf
  ansible.builtin.file:
    path: /etc/tor/torrc
    state: absent
  become: yes

- name: Configure torrc
  ansible.builtin.template:
    src: tor-config.j2
    dest: "/etc/tor/torrc"
    owner: root
    group: root
    remote_src: no

- name: Run tor service
  ansible.builtin.systemd:
    state: restarted
    daemon_reload: yes
    name: tor.service

- name: Check Tor Address
  shell: cat /var/lib/tor/electrs_hidden_service/hostname
