---

all:
  children:
    mylocalhost:
      hosts:
        localhost:
          ansible_connection: local
    eth-nodes:
      hosts:
        mia-node-01:
          ansible_host: 199.245.60.181
          ansible_connection: ssh
          ansible_port: 30022
  vars:
  ansible_user: 
  ansible_become: yes 
  ansible_become_method: sudo