---

all:
  children:
    mylocalhost:
      hosts:
        localhost:
          ansible_connection: local
    eth-nodes:
      hosts:
        mia-eth-node:
          ansible_host: 10.0.41.5
          ansible_connection: ssh
          ansible_port: 30022
  vars:
  ansible_user: wchance
  ansible_become: yes 
  ansible_become_method: sudo
