---

all:
  children:
    mylocalhost:
      hosts:
        localhost:
          ansible_connection: local
    eth-nodes:
      hosts:
        mia-eth-node:
          ansible_host: 10.0.41.5
          ansible_connection: ssh
          ansible_port: 22
        sjo-eth-node:
          ansible_host: 10.1.41.5
          ansible_connection: ssh
          ansible_port: 22
    bsc-nodes:
      hosts:
        mia-bsc-node:
          ansible_host: 10.0.41.6
          ansible_connection: ssh
          ansible_port: 22
        sjo-bsc-node:
          ansible_host: 10.1.41.6
          ansible_connection: ssh
          ansible_port: 22
    matic-nodes:
      hosts:
        mia-matic-node:
          ansible_host: 10.0.41.7
          ansible_connection: ssh
          ansible_port: 22
        sjo-matic-node:
          ansible_host: 10.1.41.7
          ansible_connection: ssh
          ansible_port: 22
    btc-nodes:
      hosts:
        mia-btc-node:
          ansible_host: 10.0.41.20
          ansible_connection: ssh
          ansible_port: 22
        sjo-btc-node:
          ansible_host: 10.1.41.20
          ansible_connection: ssh
          ansible_port: 22
    ltc-nodes:
      hosts:
        mia-ltc-node:
          ansible_host: 10.0.41.21
          ansible_connection: ssh
          ansible_port: 22
        sjo-ltc-node:
          ansible_host: 10.1.41.21
          ansible_connection: ssh
          ansible_port: 22
    bch-nodes:
      hosts:
        mia-bch-node:
          ansible_host: 10.0.41.22
          ansible_connection: ssh
          ansible_port: 22
        sjo-bch-node:
          ansible_host: 10.1.41.22
          ansible_connection: ssh
          ansible_port: 30022
    test-nodes:
      hosts:
        test-node:
          ansible_host: 199.245.60.181
          ansible_connection: ssh
          ansible_port: 30022
  vars:
  ansible_user: wchance
  ansible_become: yes 
  ansible_become_method: sudo
