---
all:
  children:
    mylocalhost:
      hosts:
        localhost:
          ansible_connection: local
    ltc-nodes:
      hosts:
        mia-ltc-node:
          ansible_host: 10.0.41.22
          ansible_connection: ssh
          ansible_port: 22
          ltc_node_ip: 10.0.41.22
        mia-ltc-electrumx:
          ansible_host: 10.0.41.23
          ansible_connection: ssh
          ansible_port: 22
          ltc_node_ip: 10.0.41.22
        sjo-ltc-node:
          ansible_host: 10.1.41.22
          ansible_connection: ssh
          ansible_port: 22
          ltc_node_ip: 10.1.41.22
        sjo-ltc-electrumx:
          ansible_host: 10.1.41.23
          ansible_connection: ssh
          ansible_port: 22
          ltc_node_ip: 10.1.41.22
  vars:
  ansible_user: wchance
  ansible_become: yes
  ansible_become_method: sudo
