---
all:
  children:
    mylocalhost:
      hosts:
        localhost:
          ansible_connection: local
    eth-nodes:
      hosts:
        mia-eth-node:
          ansible_host: 10.0.41.5
          ansible_connection: ssh
          ansible_port: 22
        sjo-eth-node:
          ansible_host: 10.1.41.5
          ansible_connection: ssh
          ansible_port: 22
    matic-nodes:
      hosts:
        mia-matic-node:
          ansible_host: 10.0.41.6
          ansible_connection: ssh
          ansible_port: 22
        sjo-matic-node:
          ansible_host: 10.1.41.6
          ansible_connection: ssh
          ansible_port: 22
    bsc-nodes:
      hosts:
        mia-bsc-node:
          ansible_host: 10.0.41.7
          ansible_connection: ssh
          ansible_port: 22
        sjo-bsc-node:
          ansible_host: 10.1.41.7
          ansible_connection: ssh
          ansible_port: 22
    btc-nodes:
      hosts:
        mia-btc-node:
          ansible_host: 10.0.41.20
          ansible_connection: ssh
          ansible_port: 22
          btc_node_ip: 10.0.41.20
        mia-btc-electrumx:
          ansible_host: 10.0.41.21
          ansible_connection: ssh
          ansible_port: 22
          btc_node_ip: 10.0.41.20
        sjo-btc-node:
          ansible_host: 10.1.41.20
          ansible_connection: ssh
          ansible_port: 22
          btc_node_ip: 10.1.41.20
        sjo-btc-electrumx:
          ansible_host: 10.1.41.21
          ansible_connection: ssh
          ansible_port: 22
          btc_node_ip: 10.1.41.20
    ltc-nodes:
      hosts:
        mia-ltc-node:
          ansible_host: 10.0.41.22
          ansible_connection: ssh
          ansible_port: 22
          ltc_node_ip: 10.0.41.22
        mia-ltc-electrumx:
          ansible_host: 10.0.41.23
          ansible_connection: ssh
          ansible_port: 22
          ltc_node_ip: 10.0.41.22
        sjo-ltc-node:
          ansible_host: 10.1.41.22
          ansible_connection: ssh
          ansible_port: 22
          ltc_node_ip: 10.1.41.22
        sjo-ltc-electrumx:
          ansible_host: 10.1.41.23
          ansible_connection: ssh
          ansible_port: 22
          ltc_node_ip: 10.1.41.22
    bch-nodes:
      hosts:
        mia-bch-node:
          ansible_host: 10.0.41.24
          ansible_connection: ssh
          ansible_port: 22
          bch_node_ip: 10.0.41.24
        mia-bch-electrumx:
          ansible_host: 10.0.41.25
          ansible_connection: ssh
          ansible_port: 22
          bch_node_ip: 10.0.41.24
        sjo-bch-node:
          ansible_host: 10.1.41.24
          ansible_connection: ssh
          ansible_port: 22
          bch_node_ip: 10.1.41.24
        sjo-bch-electrumx:
          ansible_host: 10.1.41.25
          ansible_connection: ssh
          ansible_port: 22
          bch_node_ip: 10.1.41.24
    avax-nodes:
      hosts:
        mia-avax-node:
          ansible_host: 10.0.41.8
          ansible_connection: ssh
          ansible_port: 22
        sjo-avax-node:
          ansible_host: 10.1.41.8
          ansible_connection: ssh
          ansible_port: 22
    ada-nodes:
      hosts:
        mia-ada-node:
          ansible_host: 10.0.41.9
          ansible_connection: ssh
          ansible_port: 22
        sjo-ada-node:
          ansible_host: 10.1.41.9
          ansible_connection: ssh
          ansible_port: 22
    gateway:
      hosts:
        mia-gw:
          ansible_host: 23.161.96.252
          ansible_connection: ssh
          ansible_port: 22
        sjo-gw:
          ansible_host: 190.184.199.78
          ansible_connection: ssh
          ansible_port: 22
    monitoring:
      hosts:
        mon1:
          ansible_host: 157.230.48.54
          ansible_connection: ssh
          ansible_port: 22
    testing:
      hosts:
        test-node:
          ansible_host: 147.182.254.14
          ansible_connection: ssh
          ansible_port: 22
  vars:
  ansible_user: wchance
  ansible_become: yes
  ansible_become_method: sudo
