- name: Add admin group
  group:
    name: admin
    state: present

- name: Add local user
  user:
    name: wchance
    group: admin
    shell: /bin/bash
    home: /home/wchance
    create_home: yes
    state: present

- name: Add SSH public key for user
  authorized_key:
    user: wchance
    key: "{{ lookup('file', '~/.ssh/authorized_keys') }}"
    state: present

- name: Add sudoer rule for local user
  copy:
    dest: /etc/sudoers.d/wchance
    src: /etc/sudoers.d/wchance
    owner: wchance
    group: root
    mode: 0440
    validate: /usr/sbin/visudo -csf %s
