---
- name: Install update
  apt:
    update_cache: yes

- name: Install wget
  apt:
    name: wget
    state: present

- name: Install curl
  apt:
    name: curl
    state: present

- name: Install automake
  apt:
    name: automake
    state: present

- name: Install build-essential
  apt:
    name: build-essential
    state: present

- name: Install pkg-config
  apt:
    name: pkg-config
    state: present

- name: Install libffi-dev
  apt:
    name: libffi-dev
    state: present

- name: Install libgmp-dev
  apt:
    name: libgmp-dev
    state: present

- name: Install libssl-dev
  apt:
    name: libssl-dev
    state: present

- name: Install libtinfo-dev
  apt:
    name: libtinfo-dev
    state: present

- name: Install libsystemd-dev
  apt:
    name: libsystemd-dev
    state: present

- name: Install zlib1g-dev
  apt:
    name: zlib1g-dev
    state: present

- name: Install make
  apt:
    name: make
    state: present

- name: Install g++
  apt:
    name: g++
    state: present

- name: Install tmux
  apt:
    name: tmux
    state: present

- name: Install git
  apt:
    name: git
    state: present

- name: Install jq
  apt:
    name: jq
    state: present

- name: Install libncursesw5
  apt:
    name: libncursesw5
    state: present

- name: Install libtool
  apt:
    name: libtool
    state: present

- name: Install autoconf
  apt:
    name: autoconf
    state: present

- name: Install libcurl
  apt:
    name: libcurl4
    state: present

- name: Install unzip
  apt:
    name: unzip
    state: present
