---
- name: Uncompress Ogmios
  ansible.builtin.unarchive:
    src: https://github.com/CardanoSolutions/ogmios/releases/download/v{{ ogmios_version }}/ogmios-v{{ ogmios_version }}-x86_64-linux.zip
    dest: /tmp
    remote_src: yes

- name: Copy binary
  shell: cp /tmp/bin/ogmios {{ root_dir }}/.local/bin/

- name: Change ownership
  shell: chown {{ ansible_user }}:{{ ansible_user }} {{ root_dir }}/.local/bin/ogmios

- name: Change permission
  shell: chmod +x  {{ root_dir }}/.local/bin/ogmios

- name: Configure systemd
  ansible.builtin.template:
    src: ogmios-systemd-config.j2
    dest: /etc/systemd/system/ogmios.service
    owner: root
    group: root
    remote_src: no

- name: Configure systemd (symlink)
  ansible.builtin.file:
    src: /etc/systemd/system/ogmios.service
    dest: /etc/systemd/system/multi-user.target.wants/ogmios.service
    owner: root
    group: root
    state: link

- name: Run ogmios service
  ansible.builtin.systemd:
    state: restarted
    daemon_reload: yes
    name: ogmios.service
