---

- name: Install BCH ElectrumX dependencies
  include_tasks: 
    file: install-bch-electrumx-dep.yml
    apply:
      tags: 
        - never
        - install-bch-electrumx-dep
  tags:
    - never 
    - install-bch-electrumx-dep

- name: Install BCH Core
  include_tasks: 
    file: install-bch-core.yml
    apply:
      tags: 
        - never
        - install-bch-core
  tags:
    - never 
    - install-bch-core

- name: Install BCH ElectrumX
  include_tasks: 
    file: install-bch-electrumx.yml
    apply:
      tags: 
        - never
        - install-bch-electrumx
  tags:
    - never 
    - install-bch-electrumx
