---

- name: "install dependencies for electrumX starting"
  debug:
    msg: "START!"

- name: "install packages - wait few minutes"
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop:
    - git
    - python3
    - python3-venv
    - python3-aiohttp
    - pip
    - virtualenv
    - daemontools

- name: "use module pip for install python librairy"
  pip:
    name: "{{ item }}"
    state: present
  with_items:
    - pylru
    - plyvel
    - aiorpcx

- name: "check if plyvel correctly installed"
  shell: python3 -c 'import plyvel'
  register: check_plyvel_status
