---

- name: Install Dependency
  include_tasks: 
    file: install-dependency.yml
    apply:
      tags: 
        - never
        - install-dependency-electrum-ltc
  tags:
    - never 
    - install-dependency-electrum-ltc

- name: Install Ltccore
  include_tasks: 
    file: install-ltccore.yml
    apply:
      tags: 
        - never
        - install-ltccore
  tags:
    - never 
    - install-ltccore

- name: Install Electrum
  include_tasks: 
    file: install-electrumx.yml
    apply:
      tags: 
        - never
        - install-ltc-electrum
  tags:
    - never 
    - install-ltc-electrum
